docs(rest-api-client): change any links referred Kintone Developer Program
kintone/js-sdk pull request #1218
Opened 2021-11-19 05:32 UTC by chick-p

## Why

Kintone Developer Program will be hosted on a brand new website.

Ref. https://developer.kintone.io/hc/en-us/articles/4408520355481

## What

In @kitnone/rest-api-client  documents, changed the referencing links.

## How to test

N/A

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [x] Passed `yarn lint` and `yarn test` on the root directory.

2021-12-07 01:54 UTC, mshrtsr requested changes
Thank you for your PR!
I left some comments. Please check it.

2021-12-07 01:54 UTC, mshrtsr commented on packages/rest-api-client/docs/app.md
> +| properties.{fieldCode}.referenceTable.fliterCond             |      String      |                             | The "Filter" setting, in a query format.<br />Check [Query Operators and Functions](h
TODO: fix typo `fliterCond` (fix in another PR)

2021-12-07 04:05 UTC, chick-p commented
@mshrtsr 
Thank you for your review. I've applied your comments.

2021-12-13 02:01 UTC, mshrtsr approved these changes
LGTM 💯

2021-12-13 02:10 UTC, merged

2021-12-13 02:17 UTC, mshrtsr commented on packages/rest-api-client/docs/app.md
> +| properties.{fieldCode}.referenceTable.fliterCond             |      String      |                             | The "Filter" setting, in a query format.<br />Check [Query Operators and Functions](h
fix in #1251