fix(dts-gen): apply eslint to generated `*.d.ts file`
kintone/js-sdk pull request #1266
Opened 2021-12-21 06:59 UTC by chick-p

## Why

Fixed https://github.com/kintone/js-sdk/issues/1231

## What

apply ESLint to generated `*.d.ts file`

## How to test

```
yarn build
node dist/index.js --app-id 1 --type-name SampleFields --namespace company.name.types -o sample-fields.d.ts
```

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [x] Passed `yarn lint` and `yarn test` on the root directory.

2022-05-19 23:39 UTC, ueokande requested changes

2022-05-19 23:39 UTC, ueokande commented on packages/dts-gen/src/templates/template.ts
> +const renderAsFile = async (output: string, renderInput: RenderInput) => {
replace `fs.writeFileSync` at the bottom of the function with promise-based api.

2022-05-19 23:39 UTC, ueokande commented on packages/dts-gen/src/templates/template.ts
> +  const prettySource = prettier.format(eslintOutput, {
why not use `@cybozu/eslint-config/presets/typescript-prettier`?

2022-05-19 23:39 UTC, ueokande commented on packages/dts-gen/src/templates/template.ts
> +    .join("");
This joining has a strangeness because we do not want to join the result code here. We expect that the result has a single element, and the method returns it. Access the first element explicitly (check the result count if needed before, but not required).

2022-05-19 23:39 UTC, ueokande commented on packages/dts-gen/src/templates/template.ts
> +  const eslintResult = await eslint.lintText(tsExpression.tsExpression());
To guard against unexpected errors, raise an error if the results contain non-fixable errors, such as syntax errors.

2022-05-20 04:17 UTC, mshrtsr commented on packages/dts-gen/src/templates/template.ts
> +const renderAsFile = async (output: string, renderInput: RenderInput) => {
fixed in 88447a72f89aadc64b3a2c6aa52ee5ee66d74bf2 .

2022-05-20 04:17 UTC, mshrtsr commented on packages/dts-gen/src/templates/template.ts
> +    .join("");
fixed in https://github.com/kintone/js-sdk/pull/1266/commits/3cd1aa79ad96f980a7de385f11d2f37f6ccf93a7

2022-05-20 04:32 UTC, mshrtsr commented on packages/dts-gen/src/templates/template.ts
> +  const prettySource = prettier.format(eslintOutput, {
fixed in https://github.com/kintone/js-sdk/pull/1266/commits/d6abfa9dc4a3557985c84711cafc344ed31a0d19

2022-05-20 04:37 UTC, mshrtsr commented on packages/dts-gen/src/templates/template.ts
> +  const eslintResult = await eslint.lintText(tsExpression.tsExpression());
fixed in https://github.com/kintone/js-sdk/pull/1266/commits/3cd1aa79ad96f980a7de385f11d2f37f6ccf93a7
(If eslintResult does not have the `output` property, original code is used.)

2022-05-20 06:42 UTC, ueokande commented on packages/dts-gen/src/templates/template.ts
> +  await fs.promises.writeFile(path.join(process.cwd(), output), prettySource);
```suggestion
  await fs.promises.writeFile(outputPath, prettySource);
```

2022-05-20 09:01 UTC, merged