ci: migrate to release-please
kintone/js-sdk pull request #2172
Opened 2023-07-09 09:10 UTC by hung-cybo

## Why

We want to migrate to release-please, so that we can easy to check the changes to be released

## What

- [ ] Release PR is created automatically by release-please

## How to test

N/A

## Checklist

- [ ] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [ ] Passed `yarn lint` and `yarn test` on the root directory.

2023-07-11 06:01 UTC, mshrtsr requested changes
@hung-cybo 
Thank you for your PR!!
I added comments to request some changes.

2023-07-11 06:56 UTC, hung-cybo commented on .github/workflows/release-please.yml
> +jobs:
@mshrtsr 

Thank you for your notice.
I added the publish job.

2023-07-11 10:46 UTC, mshrtsr requested changes
@hung-cybo 
We need some more steps to make the release job work correctly:)
Please check my comments.

2023-07-11 10:46 UTC, mshrtsr commented on .github/workflows/release-please.yml
> +          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
MUST: Please use the following command instead of `yarn publish`

```
yarn run lerna publish from-package --no-push --no-verify-access --yes
```

## Description

The following steps depend on lerna.
We cannot remove lerna until migration to pnpm.

### yarn build

The command `yarn build` depend on lerna.
Use `yarn workspaces run build` command instead to remove this dependency.

With pnpm, we can use recursive option: `pnpm -r build`.
https://pnpm.io/cli/recursive

### yarn publish

The `yarn publish` command failed because it tried to publish the root directory.

```
❯ yarn publish
yarn publish v1.22.19
error Package marked as private, not publishing.
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
```

There is no option to publish recursively with yarn.
https://classic.yarnpkg.com/lang/en/docs/cli/publish/

So at this time, please run the following command instead at this time.

```
yarn run lerna publish from-package --no-push --no-verify-access --yes
```

https://github.com/lerna/lerna/tree/main/libs/commands/publish#readme

With pnpm, we can use `pnpm -r publish`
https://pnpm.io/cli/publish

2023-07-11 10:46 UTC, mshrtsr commented on .github/workflows/release-please.yml
> +      pull-requests: write
MUST: We need to specify `outputs` here to use `${{ needs.release.outputs.release_created }}` on publish job.

```suggestion
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
```

2023-07-11 10:46 UTC, mshrtsr commented on .github/workflows/release-please.yml
> +  publish:
NITS: Please specify the job name as same as the release job.

```suggestion
  publish:
    name: Publish to npm
```

2023-07-11 11:38 UTC, hung-cybo commented on .github/workflows/release-please.yml
> +          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
@mshrtsr 

Great. Thank you so much for your info.

For `yarn build`, I do not change to `yarn workspaces run build`.
Reason:
- The new command is run sequentially (parallel is only supported in yarn v2, [ref](https://github.com/yarnpkg/yarn/issues/6689#issuecomment-753648699))
- We still need to use `lerna` for the Publish job.

For `yarn publish`, I updated following your suggestion.
In addition, I also add more steps for Configure git user and npm user.
I'm not sure whether these steps are necessary. So, please help me to check it.
Thank you.

2023-07-12 07:24 UTC, mshrtsr approved these changes
LGTM 👍

2023-07-12 07:24 UTC, merged