build: detect unavailable deps for NodeJS
kintone/js-sdk pull request #2381
Opened 2023-11-06 08:57 UTC by tuanphamcybozu

## Why
- Detect if our code uses the browser-only function/package in the build for Node.js.

## What
- Create a separate tsconfig file for compiling in the build for Node.js

## How to test
```
$ cd packages/rest-api-client
$ pnpm build
```

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [x] Passed `pnpm lint` and `pnpm test` on the root directory.

2023-11-06 08:57 UTC, tuanphamcybozu commented
This code for testing:
https://github.com/kintone/js-sdk/pull/2381/files#diff-9324125a349b923ca3bf2ff7a4597d3195c66af433a0debd4bbe193200ca0a0aR9-R11

I will remove it when the review is completed.

2023-11-06 10:25 UTC, mshrtsr requested changes

2023-11-06 10:25 UTC, mshrtsr commented on packages/rest-api-client/package.json
> +    "compile:node": "tsc --build --force tsconfig.node.json",
Because all the source files are transpiled with `tsconfig.json`, we don't need to generate output with `tsconfig.node.json`.
(The `src/**/node.ts` and `UnsupportedPlatformError.ts` are generated twice)

The `tsconfig.node.json` will be only for type checking.

```suggestion
    "build": "run-p compile typecheck",
    "compile": "tsc --build --force tsconfig.json",
    "typecheck": "tsc --build --force tsconfig.node.json",
```

In addition, we want to find browser-only dependencies not only on `node.ts` and `UnsupportedPlatformError.ts` but also all the files excluding `browser.ts` and its related files.

2023-11-07 09:11 UTC, tuanphamcybozu commented
> `tsconfig.typecheck.json`: A config to run type-check for the source files for the Node.js environment
Excluding test files from the build
`tsconfig.typecheck.json` should be `tsconfig.typecheck.node.json`, right?

2023-11-07 09:28 UTC, mshrtsr commented
@tuanphamcybozu 

> > `tsconfig.typecheck.json`: A config to run type-check for the source files for the Node.js environment
> > Excluding test files from the build
> 
> `tsconfig.typecheck.json` should be `tsconfig.typecheck.node.json`, right?

Exactly! I fixed the PR body!

2023-11-08 03:23 UTC, tuanphamcybozu commented on packages/rest-api-client/src/platform/browser.ts
> +  const options: BlobPropertyBag = {};
@mshrtsr 
What happens if we still use BlobOptions?

2023-11-08 03:25 UTC, tuanphamcybozu commented on packages/rest-api-client/tsconfig.typecheck.node.json
> +  "compilerOptions": {
When extends `./tsconfig.typecheck.json` and override `compilerOptions`,
`noEmit: true` is still applied for `tsconfig.typecheck.node.json`, is it right?

2023-11-08 03:28 UTC, tuanphamcybozu commented on packages/rest-api-client/tsconfig.json
> +    }
How do you think in case of type-checking error,
if we change the order of `typechecks` before `build`, can the process be faster?

Like this:
```
"references": [
   {
      "path": "./tsconfig.typecheck.json"
    },
    {
      "path": "./tsconfig.typecheck.node.json"
    }
    {
      "path": "./tsconfig.build.json"
    },
    {
      "path": "./tsconfig.build.esm.json"
    },
]
```

2023-11-08 04:31 UTC, mshrtsr commented on packages/rest-api-client/src/platform/browser.ts
> +  const options: BlobPropertyBag = {};
@tuanphamcybozu 
The `BlobOptions` is the custom type defined in `src/types/global/index.d.ts`.
The `Blob` and `BlobPart` types are also defined there.
https://github.com/kintone/js-sdk/blob/b6622d63083d0f23287ee97a75e052234d776b85/packages/rest-api-client/types/global/index.d.ts

Actually, this Blob is the Blob of DOM API, and we can use the types in `lib.dom.d.ts`.
https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob
Using our custom type might cause a mismatch between our code and the actual DOM API.
So I removed these custom types and started using types from `lib.dom.d.ts`.

2023-11-08 05:10 UTC, mshrtsr commented on packages/rest-api-client/tsconfig.typecheck.node.json
> +  "compilerOptions": {
@tuanphamcybozu 
I couldn't find this behavior in the documentation.
https://www.typescriptlang.org/tsconfig#extends

But now, yes.
As you can see for the `compilerOptions.lib`, each property of the `compilerOptions` object is inherited.

2023-11-08 05:35 UTC, mshrtsr commented on packages/rest-api-client/tsconfig.json
> +    }
@tuanphamcybozu 
I checked swapping the order, but there was no significant difference in elapsed time.
Even if typecheck is failed with `./tsconfig.typecheck.node.json`, the build for `./tsconfig.build.json` will run and generate output.

2023-11-08 06:26 UTC, tuanphamcybozu reviewed
LGTM

2023-11-08 06:40 UTC, mshrtsr approved these changes

2023-11-08 06:42 UTC, merged