chore(rest-api-client): Add info about the maximum offset value of getAllRecordsWithOffset is missed in Readme
kintone/js-sdk pull request #2497
Opened 2024-01-12 03:59 UTC by minh-nguyen1985

…tAllRecordsWithOffset in Readme

## Why

Info about the maximum offset value of getAllRecordsWithOffset is missed in Readme

## What

Add info about maximum offset value of getAllRecordsWithOffset into Readme

## How to test

N/A

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [x] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [x] Passed `pnpm lint` and `pnpm test` on the root directory.

2024-01-12 07:19 UTC, hung-cybo commented on packages/rest-api-client/docs/record.md
> +:warning: **If you'd like to get over 10000 records, please consider using [getAllRecordsWithCursor](#getAllRecordsWithCursor) instead.**
@minh-nguyen1985 

As the description of this API `Retrieves details of all records from an app`, It means that when using this API, It will retrieve all records of the specific app. The user can not decide the number of records that will be returned.

And, the fact is the error will occur if the app has over 10.000 records. So, I think we can write it to the warning message. It's easier to understand for the user.

Please consider it.
Thank you.

2024-01-12 08:32 UTC, hung-cybo approved these changes
LGTM

2024-01-16 11:02 UTC, mshrtsr requested changes

2024-01-16 11:02 UTC, mshrtsr commented on packages/rest-api-client/docs/record.md
> +:warning: **If the app has over 10.000 records, please consider using [getAllRecordsWithCursor](#getAllRecordsWithCursor) instead.**
NITS: We use American English in our repository, so please use commas for the three digit separator.

```suggestion
:warning: **If the app has over 10,000 records, please consider using [getAllRecordsWithCursor](#getAllRecordsWithCursor) instead.**
```

2024-01-17 01:17 UTC, mshrtsr approved these changes
LGTM!!

2024-01-17 01:17 UTC, merged