chore(create-plugin): remove jQuery from the minimum template
kintone/js-sdk pull request #2513
Opened 2024-01-18 08:36 UTC by tuanphamcybozu

## Why
- jQuery is the old technology, so we don't recommend using jQuery in new projects anymore.
- We will stop using jQuery in our minimum template.

## What
- Remove jQuery from the minimum template

## How to test
- The create-plugin can generate a plugin project with an updated minimum template (without jQuery code inside)

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [x] Passed `pnpm lint` and `pnpm test` on the root directory.

2024-01-19 03:46 UTC, hung-cybo reviewed
I left some comments.
Could you please check them?
Thank you.

2024-01-19 03:46 UTC, hung-cybo commented on packages/create-plugin/src/__tests__/fixtures/manifest.json
>    "version": 1,
@tuanphamcybozu 

I think this PR should be `feat`, not `chore`, because we drop the support of jQuery, It means that we have changed the behavior of this package.

Besides, when using `feat`, the user will know about this change via changelog.

2024-01-19 03:46 UTC, hung-cybo commented on packages/create-plugin/src/manifest.ts
> +          js: templateType === "minimum" ? ["js/mobile.js"] : ["js/mobile.js"],
@tuanphamcybozu 

It's the same logic. Please remove the ternary operator.

2024-01-19 03:46 UTC, hung-cybo commented on packages/create-plugin/templates/minimum/src/js/config.js
> -jQuery.noConflict();
@tuanphamcybozu 

After creating a new plugin with the modern template, when accessing the plugin config page, an error is thrown.

`Uncaught Error: Required elements do not exist.`

Because `$form.length` or `$form.on` are syntaxes of jQuery.
Could you please check it?
Thank you.

2024-01-23 03:25 UTC, hung-cybo commented on packages/create-plugin/templates/minimum/src/js/config.js
> +  var $form = document.querySelectorAll(".js-submit-settings");
@tuanphamcybozu 

Because we only get the first element, so I think we can use [querySelector()](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) instead.
Please consider it.
Thank you.

2024-01-23 03:56 UTC, hung-cybo approved these changes
LGTM

2024-01-23 13:26 UTC, mshrtsr requested changes
I added some change requests.

2024-01-23 13:26 UTC, mshrtsr commented on packages/create-plugin/templates/minimum/src/js/config.js
> +  var $message = document.querySelector(".js-text-message");
Adding `$` as the prefix of variables is a custom of jQuery.
Please remove that prefix.

It's common to name Element as `el` now. (`el`, `formEl`, `cancelButtonEl`)
https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#examples

2024-01-23 13:26 UTC, mshrtsr commented on packages/create-plugin/templates/minimum/src/js/config.js
> +  var $message = document.querySelector(".js-text-message");
Please use `const/let`, not `var`.
I expect you to replace these legacy/dangerous code in [the Boy Scout way](https://www.linkedin.com/pulse/leaving-code-cleaner-than-you-found-boy-scout-rule-software-chacko/).

2024-01-24 08:12 UTC, tuanphamcybozu commented
- Run test job is failed after update var to const/let 
  Because '@cybozu/eslint-config/presets/kintone-customize-es5' is in eslint configuration
- WA: 
  Remove es5 configure and add remain configuration in extends property of eslint congifuration.

2024-01-24 08:57 UTC, mshrtsr commented on packages/create-plugin/templates/minimum/.eslintrc.js
> +  plugins: ['eslint-plugin-prettier'],
We can use `prettier.js` to solve the CI error.
https://github.com/kintone/js-sdk/actions/runs/7635159605/job/20800124180#step:8:136

```suggestion
  extends: [
    '@cybozu/eslint-config/globals/kintone.js',
    '@cybozu/eslint-config/lib/base.js',
    '@cybozu/eslint-config/lib/kintone.js',
    '@cybozu/eslint-config/lib/prettier.js',
  ],
  rules: {
    'prettier/prettier': ['error', { singleQuote: true }],
    'space-before-function-paren': 0,
    'object-curly-spacing': 0,
  },
```

2024-01-24 10:11 UTC, mshrtsr approved these changes
LGTM!

2024-01-24 10:13 UTC, merged