feat(create-plugin): show prompt to choose Spanish support
kintone/js-sdk pull request #2770
Opened 2024-05-17 08:41 UTC by tuanphamcybozu

## Why
- We have started supporting Spanish (es) on plugin-manifest-validator recently.
- create-plugin has a prompt for language support, now it will support Spanish.

## What
- Add support Spanish in prompt
- Update readme
- Update manifest.json to display es field
- Update e2e test

## How to test
- `pnpm test:e2e`

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [x] Updated documentation if it is required.
- [x] Added tests if it is required.
- [x] Passed `pnpm lint` and `pnpm test` on the root directory.

2024-05-19 11:47 UTC, tasshi-me requested changes
I added Japanese prompt messages!
Please apply it!

In addition, I found error messages for plugin description seems wrong, it can be within 200 letters but 64 letters in error messages.

2024-05-19 11:47 UTC, tasshi-me commented on packages/create-plugin/src/messages.ts
> +    ja: "プラグインはスペイン語に対応していますか？",
```suggestion
    ja: "スペイン語をサポートしますか？",
```

2024-05-19 11:47 UTC, tasshi-me commented on packages/create-plugin/src/messages.ts
> +    ja: "プラグインの名前を入力してください (スペイン語) [1-64文字] (省略可)",
```suggestion
    ja: "プラグインのスペイン語名を入力してください [1-64文字] (省略可)",
```

2024-05-19 11:47 UTC, tasshi-me commented on packages/create-plugin/src/messages.ts
> +    ja: "プラグインの説明を入力してください (スペイン語) [1-200文字] (省略可)",
```suggestion
    ja: "プラグインのスペイン語の説明を入力してください [1-200文字] (省略可)",
```

2024-05-19 11:47 UTC, tasshi-me commented on packages/create-plugin/src/messages.ts
> +    ja: "プラグインの中国語の説明を64文字以内で入力してください",
```suggestion
    ja: "プラグインのスペイン語の説明を200文字以内で入力してください",
```

2024-05-19 11:47 UTC, tasshi-me commented on packages/create-plugin/src/messages.ts
>      ja: "プラグインの中国語の説明を64文字以内で入力してください",
The max letters of description seems wrong.
Can I ask you to fix it in this PR?

2024-05-19 11:47 UTC, tasshi-me commented on packages/create-plugin/src/messages.ts
> +    ja: "スペイン語のホームページURLを入力してください (省略可)",
```suggestion
    ja: "プラグインのスペイン語のWebサイトURLを入力してください (省略可)",
```

2024-05-20 03:56 UTC, hung-cybo approved these changes
LGTM

2024-05-22 03:03 UTC, tasshi-me approved these changes

2024-05-22 03:03 UTC, merged