feat(rest-api-client): add space.addThread() method
kintone/js-sdk pull request #2846
Opened 2024-06-27 07:51 UTC by shabaraba

## Why

Support addThread method to be able to add a tread to a space.

## What

- Add new method addThread
- Add unit test
- Add demo script

## How to test

Check test spec

## Checklist

- [ ] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/main/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [ ] Passed `pnpm lint` and `pnpm test` on the root directory.

2024-06-28 02:09 UTC, tasshi-me requested changes
I added two change requests.
Please check it 👍

2024-06-28 02:09 UTC, tasshi-me commented on examples/rest-api-client-demo/src/space.ts
> +    const name = "Added Thread Name";
This would be easier to understand when checking on the kintone screen if it were changed as follows!

```suggestion
    const name = "The thread added via rest-api-client";
```

2024-06-28 02:09 UTC, tasshi-me commented on packages/rest-api-client/docs/space.md
> +An empty object.
This method returns `id` as a response.
Please update this section 🙏

2024-06-28 02:47 UTC, shabaraba commented on examples/rest-api-client-demo/src/space.ts
> +    const name = "Added Thread Name";
addressed it in f0dceaac121df00fce20e8bbf53af50393ff9d9b

2024-06-28 02:47 UTC, shabaraba commented on packages/rest-api-client/docs/space.md
> +An empty object.
addressed it in f0dceaac121df00fce20e8bbf53af50393ff9d9b

2024-06-28 03:04 UTC, tasshi-me approved these changes
LGTM!!!

2024-07-08 03:50 UTC, hisasami approved these changes
LGTM!

2024-07-09 01:51 UTC, merged