Feat/add get and update method for admin notes
kintone/js-sdk pull request #2849
Opened 2024-06-28 12:34 UTC by shabaraba

## Why

## What

## How to test

## Checklist

- [ ] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/main/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [ ] Passed `pnpm lint` and `pnpm test` on the root directory.

2024-07-01 08:57 UTC, tasshi-me requested changes
I added some nitpick reviews.

In addition, can I ask you to rename the PR title to follow the conventional commit?

e.g. `feat(rest-api-client): add get and update methods for admin notes`

2024-07-01 08:57 UTC, tasshi-me commented on packages/rest-api-client/src/client/types/app/adminNotes.ts
> +export type AdminNoteForParameter = Partial<AdminNotes> & {
This type is better to be pluralized.

```suggestion
export type AdminNotesForParameter = Partial<AdminNotes> & {
```

2024-07-01 08:57 UTC, tasshi-me commented on packages/rest-api-client/src/client/__tests__/AppClient.test.ts
> +describe("AppClient: AdminNodes", () => {
Seems like a typo 👍 

```suggestion
describe("AppClient: AdminNotes", () => {
```

2024-07-02 01:43 UTC, shabaraba commented on packages/rest-api-client/src/client/types/app/adminNotes.ts
> +export type AdminNoteForParameter = Partial<AdminNotes> & {
[9a91117](https://github.com/kintone/js-sdk/pull/2849/commits/9a91117e943858effca9038f91ef46d61e541efd)

2024-07-02 01:43 UTC, shabaraba commented on packages/rest-api-client/src/client/__tests__/AppClient.test.ts
> +describe("AppClient: AdminNodes", () => {
[feb0ff1](https://github.com/kintone/js-sdk/pull/2849/commits/feb0ff14317bbcd7a03cb7bc7a1e99a535f120f7)

2024-07-05 04:59 UTC, tasshi-me approved these changes

2024-07-24 04:27 UTC, merged