feat(rest-api-client): update space.getSpace method
kintone/js-sdk pull request #2876
Opened 2024-07-12 07:59 UTC by shabaraba

## Why

With the official release of the June 2024 version, the 'permissions' parameter was added in the response body of Get Space API.

## What

- Update the type of Space to add 'permissions' parameter.
  - In addition, the following parameters were missing, so they were also added to the type definition:
    - showAnnouncement
    - showThreadList
    - showAppList
    - showMemberList
    - showRelatedLinkList
- update doc for space.getSpace.

## How to test

1. Create a space on UI.
2. Exec space.getSpace method
3. Check to include the `permissions` parameter in the response
4. Check to be able to access `permissions` parameter of the value of the response.
5. 
## Checklist

- [ ] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/main/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [ ] Passed `pnpm lint` and `pnpm test` on the root directory.

2024-07-12 08:03 UTC, shabaraba commented on packages/rest-api-client/src/client/types/space/index.ts
> +  permissions: Permissions;
`permissions`パラメータに対して`Permission`型だと配列で返りそうに受け取られるので、型名も複数形にしています。

2024-07-17 05:06 UTC, tasshi-me requested changes
1箇所だけ変更依頼を追加しました！

2024-07-17 05:06 UTC, tasshi-me commented on packages/rest-api-client/src/client/types/space/index.ts
> +  permissions: Permissions;
良さそうです！

2024-07-17 05:06 UTC, tasshi-me commented on packages/rest-api-client/src/client/types/space/index.ts
> +  showRelatedLinkList: boolean;
これらのプロパティはnullableなので`boolean | null`が良さそうです！
https://kintone.dev/en/docs/kintone/rest-api/spaces/get-space/#response-parameters

2024-07-17 05:53 UTC, shabaraba commented on packages/rest-api-client/src/client/types/space/index.ts
> +  showRelatedLinkList: boolean;
[6b6bf97](https://github.com/kintone/js-sdk/pull/2876/commits/6b6bf977a5119f8255904562e0ea527beb61c99f)

2024-07-17 05:53 UTC, shabaraba commented
@tasshi-me  
ありがとうございます、見逃していました :bow:

2024-07-17 05:58 UTC, tasshi-me approved these changes
LGTM!

2024-07-25 04:27 UTC, merged