feat(rest-api-client): Add method of space.updateSpace
kintone/js-sdk pull request #2884
Opened 2024-07-17 00:24 UTC by shabaraba

## Why

## What

## How to test

## Checklist

- [ ] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/main/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [ ] Passed `pnpm lint` and `pnpm test` on the root directory.

2024-07-17 06:20 UTC, tasshi-me requested changes
2箇所レビュー追加しました！ 👍

2024-07-17 06:20 UTC, tasshi-me commented on packages/rest-api-client/src/client/types/space/index.ts
> +  permissions: Permissions;
スペースID以外は省略可能なのでOptionalですね！

```suggestion
  name?: string;
  isPrivate?: boolean;
  useMultiThread?: boolean;
  fixedMember?: boolean;
  showAnnouncement?: boolean;
  showThreadList?: boolean;
  showAppList?: boolean;
  showMemberList?: boolean;
  showRelatedLinkList?: boolean;
  permissions?: Permissions;
```

https://cybozu.dev/ja/kintone/docs/rest-api/spaces/update-space/#request

2024-07-17 06:20 UTC, tasshi-me commented on packages/rest-api-client/docs/space.md
> +| showRelatedLinkList   |     Boolean      |          | The display status for the Related Apps & Spaces widget.<br /><strong>true</strong>: The Related Apps & Spaces widget is displayed.<br /><stron
こちらはUpdate側なので`null`の説明は不要そうです！

2024-07-18 02:29 UTC, shabaraba commented on packages/rest-api-client/src/client/types/space/index.ts
> +  permissions: Permissions;
ありがとうございます、見逃してました
[89e6ee6](https://github.com/kintone/js-sdk/pull/2884/commits/89e6ee60c50ae58831bfe26484917a7cb28ecc69)

2024-07-18 02:29 UTC, shabaraba commented on packages/rest-api-client/docs/space.md
> +| showRelatedLinkList   |     Boolean      |          | The display status for the Related Apps & Spaces widget.<br /><strong>true</strong>: The Related Apps & Spaces widget is displayed.<br /><stron
[89e6ee6](https://github.com/kintone/js-sdk/pull/2884/commits/89e6ee60c50ae58831bfe26484917a7cb28ecc69)

2024-07-18 07:39 UTC, tasshi-me approved these changes
LGTM!

2024-07-24 05:39 UTC, merged