feat(rest-api-client): add method of plugin.getPlugins
kintone/js-sdk pull request #2896
Opened 2024-07-25 04:30 UTC by shabaraba

## Why

Support plugin.getPlugins method to be able to get the list of plug-ins imported into Kintone.

## What

- Add a document for the new method.

## How to test

Check test spec.

## Checklist

- [ ] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/main/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [ ] Passed `pnpm lint` and `pnpm test` on the root directory.

2024-07-25 10:43 UTC, tasshi-me requested changes
レビュー2箇所追加しました！
確認お願いします！

2024-07-25 10:43 UTC, tasshi-me commented on packages/rest-api-client/docs/plugin.md
> +Gets the list of plug-ins that have been deleted from Kintone, but have already been added to Apps.
NOTE: この説明だとアプリテンプレートからアプリを追加した場合がカバーされてないけどdevnet側も同じなのでこれでOK。

2024-07-25 10:43 UTC, tasshi-me commented on packages/rest-api-client/src/client/PluginClient.ts
> +    const path = this.buildPath({ endpointName: "plugins" });
NOTE: ゲストスペース関係ないAPIなので`buildPath`でOK

2024-07-25 10:43 UTC, tasshi-me commented on packages/rest-api-client/src/client/types/plugin/index.ts
> +  revision: string;
MUST: ここ`revision`じゃなくて`version`ですね！！！

```suggestion
  version: string;
```

2024-07-25 10:43 UTC, tasshi-me commented on packages/rest-api-client/src/client/__tests__/PluginClient.test.ts
> +      auth: { type: "apiToken", apiToken: "foo" },
Mockしてるので動くんですけど、プラグイン系APIはAPIトークン非対応なので、`auth`はパスワード認証にしておくほうが良さそうです！
（これまで見逃してたかも）

2024-07-26 01:12 UTC, shabaraba commented on packages/rest-api-client/src/client/types/plugin/index.ts
> +  revision: string;
すみません、全然気づけていませんでした :bow: 
suggested changeを取り込みました

2024-07-26 01:13 UTC, shabaraba commented on packages/rest-api-client/src/client/__tests__/PluginClient.test.ts
> +      auth: { type: "apiToken", apiToken: "foo" },
9b78a7a595ba74acf5491379a9091e84a93d40d0 で対応しました。  
SpaceClientも同様でしたので一緒にパスワード認証に変更しています。

2024-07-26 05:44 UTC, shabaraba commented on packages/rest-api-client/src/client/types/index.ts
> +export * from "./plugin";
@tasshi-me 
このファイルでtype配下のものをexportしているのに気づいたので、pluginも追加しています

2024-08-01 02:41 UTC, tasshi-me approved these changes
LGTM！

2024-08-02 05:31 UTC, merged