docs: add typescript support version
kintone/js-sdk pull request #522
Opened 2020-11-06 06:12 UTC by shisama

## Why

This shows TypeScript version explicitly.

## What

The version is written in typescript.md

## How to test

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [ ] Passed `yarn lint` and `yarn test` on the root directory.

2020-11-09 13:12 UTC, shisama commented on .github/ISSUE_TEMPLATE/typescript.md
> +name: "TypeScript Issue"
What is an emoji for TypeScript issue?

2020-11-09 13:12 UTC, shisama commented on .github/ISSUE_TEMPLATE/typescript.md
> +
Are these necessary?

2020-11-09 13:14 UTC, shisama commented on .github/ISSUE_TEMPLATE/typescript.md
> +- Babel: 0.0.0 <!-- if you use Babel. If not, delete this line. -->
Is the Babel version necessary?

2020-11-10 05:01 UTC, koba04 commented on .github/ISSUE_TEMPLATE/typescript.md
> +name: "TypeScript Issue"
What about 🙈 ? (That has no meaning, but cute)

2020-11-10 05:41 UTC, koba04 commented on .github/ISSUE_TEMPLATE/typescript.md
> +name: "TypeScript Issue"
```suggestion
name: "🙈 TypeScript Issue"
```

2020-11-10 05:43 UTC, koba04 requested changes
@shisama Thank you! I've put a suggestion for the emoji. Could you fix the error in the lint task in CI?

2020-11-10 06:20 UTC, shisama commented
@koba04 Thank you for your suggestion. I committed it and fixed the lint error.

2020-11-10 06:22 UTC, koba04 approved these changes
👍👍👍

2020-11-10 06:22 UTC, merged