feat: support --base-url and KINTONE_BASE_URL
kintone/js-sdk pull request #536
Opened 2020-11-18 02:48 UTC by koba04

## Why

This is a part of #530.

## What

I've added `--base-url` option and support the `KINTONE_BASE_URL` environment value.

## How to test

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [x] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [ ] Passed `yarn lint` and `yarn test` on the root directory.

2020-11-30 12:49 UTC, shisama commented on packages/dts-gen/src/cli-parser-test.ts
> +import { parse } from "./cli-parser";
If this should run when `yarn test` is executed, `cli-parser.test.ts` is the correct file name. Now, this file doesn't run when `yarn test` is executed.

2020-11-30 12:50 UTC, shisama commented on packages/dts-gen/src/cli-parser-test.ts
> +            expect(args.proxyHost).toBe("PROXY_HOST");
Maybe `typeName` is forgot.

2020-11-30 13:01 UTC, shisama commented on packages/dts-gen/src/cli-parser-test.ts
> +                    "https://example2.kintone.com",
This test fails since `baseUrl` is specified. This URL literal may not need.
```suggestion
```

2020-11-30 13:20 UTC, shisama commented on packages/dts-gen/src/cli-parser.ts
> +    } as any;
```suggestion
    } as ParsedArgs;
```

2020-11-30 13:26 UTC, shisama requested changes
@koba04 Good job! Thank you for fixing this. I left some comments. Please take a look at them.

2020-12-01 01:14 UTC, koba04 commented on packages/dts-gen/src/cli-parser.ts
> +    } as any;
👍  Unfortunately, the type cannot be casted to ParsedArgs directly because the type of `parsedArgs` is `commander.Command`, so I've casted the type at the `program.parse()`.
https://github.com/kintone/js-sdk/pull/536/commits/3d3f6bb541d2fb303f0da5ccd45c3e007684d7b6#diff-75257f38fd4cf6ea78b0699d85fb15d6e6a998407380ff314282ce47948ae580R101-R104

2020-12-01 01:16 UTC, koba04 commented
@shisama Thank you for your review 🌟  I've addressed the points you've pointed out!

2020-12-01 02:05 UTC, shisama commented on packages/dts-gen/src/cli-parser.ts
> +    } as any;
Oh, sorry. I've tried this now on my local and I realized this is wrong.

2020-12-01 02:11 UTC, shisama commented on packages/dts-gen/src/cli-parser.ts
> +    } as any;
BTW, the `parsedArgs` variable has properties that `ParsedArgs` does not have. For example, `host`. Is it OK to destructure the object (`...parsedArgs`)?

2020-12-01 03:15 UTC, koba04 commented on packages/dts-gen/src/cli-parser.ts
> +    } as any;
That's a good point. I've fixed it. 👍

2020-12-01 03:16 UTC, shisama approved these changes
@koba04 👍 Thank you for fixing what I pointed out.

2020-12-01 03:29 UTC, merged

2020-12-01 05:08 UTC, koba04 commented
Thank for the good feedbacks!!! 🎉 🎉 🎉